### ISSUE TITLE
hadoop command not found

### ISSUE THREAD

**Issue by AndriiOmelianenko** [mesosphere/dcos-hdfs#3] opened 2015-07-20 13:57 UTC
I have installed HDFS via DCOS CLI.
Due to this doc (https://docs.mesosphere.com/services/hdfs/) I can log in into any slave node and use hdfs with`$ hadoop fs -ls hdfs://hdfs/` straight away. But I can't. 
```
$ hadoop fs -ls hdfs://hdfs/
bash: hadoop: command not found...
```

However, if I add `/opt/mesosphere/packages/hadoop--a0b14ad939d0ed373688435552ff63f724608a78/bin/` to `PATH` variable it works. 

Is this hdfs or documentation issue?
Can any one help me?

**Comment by elingg** [comment] 2015-07-20 17:23
hello @AndriiOmelianenko, yes, I can help you out. Is the HDFS Service displaying as Green/Healthy in the DCOS UI? If yes, you should be able to log into the slave nodes and run the hadoop commands. If this is not working, but the service is healthy, we can work together and investigate further.

**Comment by elingg** [comment] 2015-07-20 20:07
I just tested with the latest build and was unable to reproduce as well..

**Comment by AndriiOmelianenko** [comment] 2015-07-20 20:19
@elingg yes, hdfs is displaying as `Healthy` in DCOS UI. I can access hdfs from slaves, but only from specific directories, like `/opt/mesosphere/packages/hadoop--a0b14ad939d0ed373688435552ff63f724608a78/bin/` where hadoop binaries are located. 
From any other directory (even from home dir) it displays `command not found`.

**Comment by elingg** [comment] 2015-07-20 23:07
Are you using the AWS or Azure templates @AndriiOmelianenko ?

**Comment by elingg** [comment] 2015-07-20 23:14
On Azure, there are some issues, so the following workaround is required. 
env changes:
core@slave0 ~ $ export PATH=$PATH:/opt/mesosphere/bin
core@slave0 ~ $ export JAVA_HOME=/opt/mesosphere/active/java/usr/java

On AWS, it should work out of box. Today I ran it and the command ran fine for me.

**Comment by AndriiOmelianenko** [comment] 2015-07-21 15:04
@elingg I'm using OpenStack :)

unfortunately, those exports doesn't work for me:
```
$ hadoop fs -ls /
15/07/21 15:02:38 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
15/07/21 15:02:39 WARN shortcircuit.DomainSocketFactory: The short-circuit local reads feature cannot be used because libhadoop cannot be loaded.
```

**Comment by elingg** [comment] 2015-07-21 16:00
Yes, the warning is ok. We can probably optimize to get rid of it. I will close this issue. Technically, we don't support OpenStack, but awesome to hear you got it running!

**Closed by elingg** 2015-07-21 16:00 UTC

**Comment by AndriiOmelianenko** [comment] 2015-07-21 17:10
@elingg thank you very much.

small note:
if I run `hadoop` from mesos sandbox directory it works without warnings. but I can't add this to PATH, bacause this dir isn't permanent, it depends on which node dcos decides to install hdfs executors:
```
$ /var/lib/mesos/slave/slaves/20150721-135839-3323775754-5050-13266-S0/frameworks/20150721-135839-3323775754-5050-13266-0001/executors/executor.datanode.NodeExecutor.1437490197760/runs/latest/hdfs-mesos-0.1.1/bin/hadoop fs -ls /
Found 1 items
-rw-r--r--   3 centos supergroup          5 2015-07-21 15:18 /test
```

**Comment by elingg** [comment] 2015-07-21 17:14
Are you running with or without predistributed binaries? If you are running without predistributed binaries, HDFS will create a symlink outside your sandbox and an additional sym link to /usr/bin/hadoop.

**Comment by AndriiOmelianenko** [comment] 2015-07-23 07:54
I'm not sure where predistributed binaries are located.

if I run predistributed binary (inside this one? `/opt/mesosphere/...`) it gives warning.
but when I run binary from installed hdfs package in dcos (probably from here https://github.com/mesosphere/universe) it gives no warning

**Comment by elingg** [comment] 2015-07-24 22:48
Correct, pre-distributed binaries are located in ```/opt/mesosphere/...```

**Comment by AndriiOmelianenko** [comment] 2015-07-28 16:18
so those warning are caused because config wasn't applied to pre-distributed binaries?

**Comment by elingg** [comment] 2015-08-04 00:23
Need to investigate those warnings further. Seems there is a configuration that is not being optimized, but the functionality is working correctly.

**Comment by arindamchoudhury** [comment] 2016-06-10 15:24
I have the same problem. I am testing it on AWS.
